memsim: memsim.o FIFO.o lru.o vms.o
	g++ -std=c++11 -o memsim memsim.o FIFO.o lru.o vms.o dataStructures.o

memsim.o: memsim.cpp
	g++ -std=c++11 -c memsim.cpp

FIFO.o: FIFO.cpp
	g++ -std=c++11 -c FIFO.cpp

lru.o: lru.cpp
	g++ -std=c++11 -c lru.cpp 

vms.o: vms.cpp
	g++ -std=c++11 -c vms.cpp

dataStructures.o: dataStructures.cpp
	g++ -std=c++11 -c dataStructures.cpp

clean:
	rm *.o memsim